### PR TITLE
fix TCO, add return value

### PR DESCRIPTION
**Pull request by simon300000**
Based on this Webkit Blog
https://webkit.org/blog/6240/ecmascript-6-proper-tail-calls-in-webkit/

> What is a Proper Tail Call?
>
> ...
>
> * The return value of the called function is returned by the calling function.

If a function has no return value, it would not be optimized in webkit

Safari: 13.0 (15608.1.31.1.2)
Safari Technology Preview: Release 87 (Safari 13.0, WebKit 15608.1.33.2)

Before:
image

With this PR:
image

Chrome: 77.0.3850.0
No change

Node.js: v12.4.0
No change

Firefox does not work, shows loading all the time

### CODE REVIEW

**Comment by ruanyf** [comment]
As I know, Chrome doesn't support TCO yet. http://kangax.github.io/compat-table/es6/

**Comment by simon300000** [comment]
@ruanyf This is not about Chrome, this test case is not considered as “proper tail call” in WebKit.
So it will show webkit does not support TCO even webkit does support TCO.

Which means it will produce a wrong result.

This is a screenshot from the link you provide.
164AB87D-8BF6-492B-9950-870BC07A824E

**Comment by simon300000** [comment]
Same browser tested with this repo and the link you provided.
7A7F0B5A-3FF3-441D-B57D-28E06E509B76
831FCA65-6DD8-4A23-92B8-33667F59170A

**Comment by ruanyf** [comment]
Sorry, I took it wrong. You are right that the original code is nor correct for Webkit.

**Pull request merged**
